apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: monitoring-operator-centreonservice-viewer-role
rules:
- apiGroups:
  - monitor.k8s.webcenter.fr
  resources:
  - centreonservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitor.k8s.webcenter.fr
  resources:
  - centreonservices/status
  verbs:
  - get
