apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "monitor.k8s.webcenter.fr/v1alpha1",
          "kind": "CentreonService",
          "metadata": {
            "name": "cs-sample"
          },
          "spec": {
            "activate": true,
            "host": "localhost",
            "name": "test-ping",
            "template": "template-test"
          }
        },
        {
          "apiVersion": "monitor.k8s.webcenter.fr/v1alpha1",
          "kind": "Platform",
          "metadata": {
            "name": "platform-sample"
          },
          "spec": {
            "entreonSettings": {
              "endpoint": {
                "discoverEndpoint": false
              },
              "secret": "centreon",
              "selfSignedCertificat": true,
              "url": "http://localhost/api"
            },
            "isDefault": false,
            "name": "centreon",
            "type": "centreon"
          }
        }
      ]
    capabilities: Basic Install
    categories: Monitoring
    containerImage: webcenter/monitoring-operator:v0.0.1
    createdAt: "2022-05-19T00:00:00Z"
    description: It permit to create monitoring resource on Centreon
    operators.operatorframework.io/builder: operator-sdk-v1.19.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
    repository: https://github.com/olaf-meyer/helm-operator
    support: None
  name: monitoring-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: CentreonService is the Schema for the centreonservices API
      displayName: Centreon Service
      kind: CentreonService
      name: centreonservices.monitor.k8s.webcenter.fr
      version: v1alpha1
    - description: Platform is the Schema for the platforms API
      displayName: Platform
      kind: Platform
      name: platforms.monitor.k8s.webcenter.fr
      version: v1alpha1
  description: It permit to create monitoring resource on Centreon
  displayName: monitoring-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - get
          - patch
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - monitor.k8s.webcenter.fr
          resources:
          - centreonServices
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitor.k8s.webcenter.fr
          resources:
          - centreons
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - monitor.k8s.webcenter.fr
          resources:
          - centreonservices
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitor.k8s.webcenter.fr
          resources:
          - centreonservices/finalizers
          verbs:
          - update
        - apiGroups:
          - monitor.k8s.webcenter.fr
          resources:
          - centreonservices/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - monitor.k8s.webcenter.fr
          resources:
          - platforms
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitor.k8s.webcenter.fr
          resources:
          - platforms/finalizers
          verbs:
          - update
        - apiGroups:
          - monitor.k8s.webcenter.fr
          resources:
          - platforms/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - networking.k8s.io
          resources:
          - ingresses
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: monitoring-operator-monitoring-operator
      deployments:
      - label:
          control-plane: controller-manager
        name: monitoring-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources: {}
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                env:
                - name: OPERATOR_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: LOG_LEVEL
                  value: INFO
                - name: MONITORING_PLATEFORM
                  value: centreon
                - name: MONITORING_DISABLE_SSL_CHECK
                  value: "true"
                image: webcenter/monitoring-operator:0.0.1
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 512Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: monitoring-operator-monitoring-operator
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: monitoring-operator-monitoring-operator
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - monitoring
  - centreon
  links:
  - name: Monitoring Operator
    url: https://monitoring-operator.domain
  maintainers:
  - email: linuxworkgroup@hotmail.com
    name: disaster37
  maturity: alpha
  provider:
    name: webcenter.fr
    url: https://github.com/disaster37/monitoring-operator
  version: 0.0.1
