apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    monitor.k8s.webcenter.fr/templates: '[{"namespace":"operators","name":"check-something"}]'
  name: test-ingress
spec:
  rules:
  - host: my-test.cluster.local
    http:
      paths:
      - backend:
          service:
            name: test-cb
            port:
              number: 9000
        path: /
        pathType: Prefix