package controllers

import (
	"context"
	"errors"
	"testing"
	"time"

	"github.com/disaster37/monitoring-operator/api/v1alpha1"
	"github.com/disaster37/monitoring-operator/pkg/centreonhandler"
	"github.com/disaster37/monitoring-operator/pkg/helpers"
	"github.com/disaster37/monitoring-operator/pkg/mocks"
	"github.com/disaster37/operator-sdk-extra/pkg/test"
	"github.com/golang/mock/gomock"
	"github.com/sirupsen/logrus"
	"github.com/stretchr/testify/assert"
	core "k8s.io/api/core/v1"
	k8serrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

func (t *ControllerTestSuite) TestNamespaceCentreonController() {
	key := types.NamespacedName{
		Name:      "t-namespace-" + helpers.RandomString(10),
		Namespace: "default",
	}
	ns := &core.Namespace{}
	data := map[string]any{}

	testCase := test.NewTestCase(t.T(), t.k8sClient, key, ns, 5*time.Second, data)
	testCase.Steps = []test.TestStep{
		doCreateNamespaceStep(),
		doUpdateNamespaceStep(),
		doDeleteNamespaceStep(),
	}
	testCase.PreTest = doMockNamespace(t.mockCentreonHandler)

	testCase.Run()

}

func doMockNamespace(mockCS *mocks.MockCentreonHandler) func(stepName *string, data map[string]any) error {
	return func(stepName *string, data map[string]any) (err error) {

		// Mock Centreon client
		mockCS.EXPECT().GetService(gomock.Any(), gomock.Any()).AnyTimes().Return(nil, nil)
		mockCS.EXPECT().DiffService(gomock.Any(), gomock.Any()).AnyTimes().Return(&centreonhandler.CentreonServiceDiff{
			IsDiff: false,
		}, nil)
		mockCS.EXPECT().CreateService(gomock.Any()).AnyTimes().Return(nil)
		mockCS.EXPECT().UpdateService(gomock.Any()).AnyTimes().Return(nil)
		mockCS.EXPECT().DeleteService(gomock.Any(), gomock.Any()).AnyTimes().Return(nil)

		return nil
	}
}

func doCreateNamespaceStep() test.TestStep {
	return test.TestStep{
		Name: "create",
		Pre: func(c client.Client, data map[string]any) error {
			csTemplate := &v1alpha1.TemplateCentreonService{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "template-namespace1",
					Namespace: "default",
				},
				Spec: v1alpha1.TemplateCentreonServiceSpec{
					Template: `
host: "localhost"
name: "ping1"
template: "template1"
macros:
  name: "{{ .name }}"
  namespace: "{{ .namespace }}"
arguments:
  - "arg1"
  - "arg2"
activate: true
groups:
  - "sg1"
categories:
  - "cat1"`,
				},
			}
			if err := c.Create(context.Background(), csTemplate); err != nil {
				return err
			}
			logrus.Infof("Create CentreonServiceTemplate template-namespace1")

			csTemplate = &v1alpha1.TemplateCentreonService{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "template-namespace2",
					Namespace: "default",
				},
				Spec: v1alpha1.TemplateCentreonServiceSpec{
					Template: `
host: "localhost"
name: "ping2"
template: "template2"
macros:
  name: "{{ .name }}"
  namespace: "{{ .namespace }}"
arguments:
  - "arg1"
  - "arg2"
activate:  true
groups:
  - "sg1"
categories:
  - "cat1"`,
				},
			}
			if err := c.Create(context.Background(), csTemplate); err != nil {
				return err
			}
			logrus.Infof("Create CentreonServiceTemplate template-namespace2")

			return nil
		},
		Do: func(c client.Client, key types.NamespacedName, o client.Object, data map[string]any) (err error) {
			logrus.Infof("=== Add new Namespace %s ===", key.Name)

			// Create namespace that refer 2 templates
			ns := &core.Namespace{
				ObjectMeta: metav1.ObjectMeta{
					Name: key.Name,
					Labels: map[string]string{
						"app": "appTest",
						"env": "dev",
					},
					Annotations: map[string]string{
						"monitor.k8s.webcenter.fr/templates": "[{\"namespace\":\"default\", \"name\": \"template-namespace1\"}, {\"namespace\":\"default\", \"name\": \"template-namespace2\"}]",
					},
				},
			}

			if err = c.Create(context.Background(), ns); err != nil {
				return err
			}

			return nil
		},
		Check: func(t *testing.T, c client.Client, key types.NamespacedName, o client.Object, data map[string]any) (err error) {
			cs := &v1alpha1.CentreonService{}

			// Get service generated by template-namespace1
			isTimeout, err := RunWithTimeout(func() error {
				if err := c.Get(context.Background(), types.NamespacedName{Namespace: key.Name, Name: "template-namespace1"}, cs); err != nil {
					if k8serrors.IsNotFound(err) {
						return errors.New("Not yet created")
					}
					t.Fatalf("Error when get Centreon service template-namespace1: %s", err.Error())
				}
				return nil
			}, time.Second*30, time.Second*1)
			if err != nil || isTimeout {
				t.Fatalf("Failed to get Centreon service template-namespace1: %s", err.Error())
			}
			expectedCSSpec := v1alpha1.CentreonServiceSpec{
				Host:     "localhost",
				Name:     "ping1",
				Template: "template1",
				Macros: map[string]string{
					"name":      key.Name,
					"namespace": key.Name,
				},
				Arguments:  []string{"arg1", "arg2"},
				Activated:  true,
				Groups:     []string{"sg1"},
				Categories: []string{"cat1"},
			}
			assert.Equal(t, "appTest", cs.Labels["app"])
			assert.Equal(t, "template-namespace1", cs.Name)
			assert.Equal(t, "template-namespace1", cs.Labels["monitor.k8s.webcenter.fr/template-name"])
			assert.Equal(t, "default", cs.Labels["monitor.k8s.webcenter.fr/template-namespace"])
			assert.Equal(t, "[{\"namespace\":\"default\", \"name\": \"template-namespace1\"}, {\"namespace\":\"default\", \"name\": \"template-namespace2\"}]", cs.Annotations["monitor.k8s.webcenter.fr/templates"])
			assert.Equal(t, expectedCSSpec, cs.Spec)
			assert.NotEmpty(t, cs.OwnerReferences)

			// Get service generated by template-namespace2
			isTimeout, err = RunWithTimeout(func() error {
				if err := c.Get(context.Background(), types.NamespacedName{Namespace: key.Name, Name: "template-namespace2"}, cs); err != nil {
					if k8serrors.IsNotFound(err) {
						return errors.New("Not yet created")
					}
					t.Fatalf("Error when get Centreon service template-namespace2: %s", err.Error())
				}
				return nil
			}, time.Second*30, time.Second*1)
			if err != nil || isTimeout {
				t.Fatalf("Failed to get Centreon service template-namespace2: %s", err.Error())
			}
			expectedCSSpec = v1alpha1.CentreonServiceSpec{
				Host:     "localhost",
				Name:     "ping2",
				Template: "template2",
				Macros: map[string]string{
					"name":      key.Name,
					"namespace": key.Name,
				},
				Arguments:  []string{"arg1", "arg2"},
				Activated:  true,
				Groups:     []string{"sg1"},
				Categories: []string{"cat1"},
			}
			assert.Equal(t, "appTest", cs.Labels["app"])
			assert.Equal(t, "template-namespace2", cs.Labels["monitor.k8s.webcenter.fr/template-name"])
			assert.Equal(t, "default", cs.Labels["monitor.k8s.webcenter.fr/template-namespace"])
			assert.Equal(t, "[{\"namespace\":\"default\", \"name\": \"template-namespace1\"}, {\"namespace\":\"default\", \"name\": \"template-namespace2\"}]", cs.Annotations["monitor.k8s.webcenter.fr/templates"])
			assert.Equal(t, expectedCSSpec, cs.Spec)
			assert.NotEmpty(t, cs.OwnerReferences)
			return nil
		},
	}
}

func doUpdateNamespaceStep() test.TestStep {
	return test.TestStep{
		Name: "update",
		Pre: func(c client.Client, data map[string]any) error {

			logrus.Info("Update CentreonServiceTemplate templat-namespace1")
			csTemplate := &v1alpha1.TemplateCentreonService{}
			if err := c.Get(context.Background(), types.NamespacedName{Namespace: "default", Name: "template-namespace1"}, csTemplate); err != nil {
				return err
			}

			csTemplate.Spec.Template = `
host: "localhost"
name: "ping1"
template: "template1"
macros:
  name: "{{ .name }}"
  namespace: "{{ .namespace }}"
arguments:
  - "arg11"
  - "arg21"
activate: true
groups:
  - "sg1"
categories:
  - "cat1"`
			if err := c.Update(context.Background(), csTemplate); err != nil {
				return err
			}

			return nil
		},
		Do: func(c client.Client, key types.NamespacedName, o client.Object, data map[string]any) (err error) {
			logrus.Infof("=== Update Namespace %s ===", key.Name)

			if o == nil {
				return errors.New("Namespace is null")
			}
			ns := o.(*core.Namespace)

			ns.Annotations["test"] = "update"

			// Get version of current CentreonService object
			cs := &v1alpha1.CentreonService{}
			if err := c.Get(context.Background(), types.NamespacedName{Namespace: key.Name, Name: "template-namespace1"}, cs); err != nil {
				return err
			}

			data["version"] = cs.ResourceVersion

			if err = c.Update(context.Background(), ns); err != nil {
				return err
			}

			return nil
		},
		Check: func(t *testing.T, c client.Client, key types.NamespacedName, o client.Object, data map[string]any) (err error) {
			cs := &v1alpha1.CentreonService{}

			version := data["version"].(string)

			// Get service generated by template-namespace1
			isTimeout, err := RunWithTimeout(func() error {
				if err := c.Get(context.Background(), types.NamespacedName{Namespace: key.Name, Name: "template-namespace1"}, cs); err != nil {
					if k8serrors.IsNotFound(err) {
						t.Fatalf("Error when get Centreon service: %s", err.Error())
					}
					if cs.ResourceVersion == version {
						return errors.New("Not yet updated")
					}
				}
				return nil
			}, time.Second*30, time.Second*1)
			if err != nil || isTimeout {
				t.Fatalf("Failed to get Centreon service template-namespace1: %s", err.Error())
			}
			expectedCSSpec := v1alpha1.CentreonServiceSpec{
				Host:     "localhost",
				Name:     "ping1",
				Template: "template1",
				Macros: map[string]string{
					"name":      key.Name,
					"namespace": key.Name,
				},
				Arguments:  []string{"arg11", "arg21"},
				Activated:  true,
				Groups:     []string{"sg1"},
				Categories: []string{"cat1"},
			}
			assert.Equal(t, "appTest", cs.Labels["app"])
			assert.Equal(t, "[{\"namespace\":\"default\", \"name\": \"template-namespace1\"}, {\"namespace\":\"default\", \"name\": \"template-namespace2\"}]", cs.Annotations["monitor.k8s.webcenter.fr/templates"])
			assert.Equal(t, expectedCSSpec, cs.Spec)
			assert.NotEmpty(t, cs.OwnerReferences)

			return nil
		},
	}
}

func doDeleteNamespaceStep() test.TestStep {
	return test.TestStep{
		Name: "delete",
		Do: func(c client.Client, key types.NamespacedName, o client.Object, data map[string]any) (err error) {
			logrus.Infof("=== Delete Namespace %s ===", key.Name)
			if o == nil {
				return errors.New("Namespace is null")
			}
			ns := o.(*core.Namespace)

			wait := int64(0)
			if err = c.Delete(context.Background(), ns, &client.DeleteOptions{GracePeriodSeconds: &wait}); err != nil {
				return err
			}

			return nil
		},
		Check: func(t *testing.T, c client.Client, key types.NamespacedName, o client.Object, data map[string]any) (err error) {

			// We can't test in envtest that the children is deleted
			// https://stackoverflow.com/questions/64821970/operator-controller-could-not-delete-correlated-resources
			// Namespace seems can't be deleted in envtest. Block on kubernetes finalizer

			return nil
		},
	}
}
