# permissions for end users to view centreons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: centreon-viewer-role
rules:
- apiGroups:
  - monitor.k8s.webcenter.fr
  resources:
  - centreons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitor.k8s.webcenter.fr
  resources:
  - centreons/status
  verbs:
  - get
