# permissions for end users to view centreonservicegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: centreonservicegroup-viewer-role
rules:
- apiGroups:
  - monitor.k8s.webcenter.fr
  resources:
  - centreonservicegroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitor.k8s.webcenter.fr
  resources:
  - centreonservicegroups/status
  verbs:
  - get
