# permissions for end users to edit centreonservicegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: centreonservicegroup-editor-role
rules:
- apiGroups:
  - monitor.k8s.webcenter.fr
  resources:
  - centreonservicegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitor.k8s.webcenter.fr
  resources:
  - centreonservicegroups/status
  verbs:
  - get
