# All RBAC will be applied under this service account in
# the deployment namespace. You may comment out this resource
# if your manager will use a service account that exists at
# runtime. Be sure to update RoleBinding and ClusterRoleBinding
# subjects if changing service account names.
# The following RBAC configurations are used to protect
# the metrics endpoint with authn/authz. These configurations
# ensure that only authorized users and service accounts
# can access the metrics endpoint. Comment the following
# permissions if you want to disable this protection.
# More info: https://book.kubebuilder.io/reference/metrics.html
# Add cluster roles to handle custom resource by users
resources:
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- metrics_auth_role.yaml
- metrics_auth_role_binding.yaml
- metrics_reader_role.yaml
- centreonservice_editor_role.yaml
- centreonservice_viewer_role.yaml
- centreonservicegroup_editor_role.yaml
- centreonservicegroup_viewer_role.yaml
- platform_editor_role.yaml
- platform_viewer_role.yaml
- templatecentreonservice_editor_role.yaml
- templatecentreonservice_viewer_role.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
