# permissions for end users to view platforms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-viewer-role
rules:
  - apiGroups:
      - monitor.k8s.webcenter.fr
    resources:
      - platforms
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - monitor.k8s.webcenter.fr
    resources:
      - platforms/status
    verbs:
      - get
