
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: monitoring-operator
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitor.k8s.webcenter.fr
  resources:
  - centreonServices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitor.k8s.webcenter.fr
  resources:
  - centreonservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitor.k8s.webcenter.fr
  resources:
  - centreonservices/finalizers
  verbs:
  - update
- apiGroups:
  - monitor.k8s.webcenter.fr
  resources:
  - centreonservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitor.k8s.webcenter.fr
  resources:
  - platforms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitor.k8s.webcenter.fr
  resources:
  - platforms/finalizers
  verbs:
  - update
- apiGroups:
  - monitor.k8s.webcenter.fr
  resources:
  - platforms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
