# permissions for end users to view templates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: centreonservicetemplate-viewer-role
rules:
- apiGroups:
  - monitor.k8s.webcenter.fr
  resources:
  - templates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitor.k8s.webcenter.fr
  resources:
  - templates/status
  verbs:
  - get
