apiVersion: v1
kind: Service
metadata:
  name: centreon-test
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/instance: centreon-test
  sessionAffinity: None
  type: NodePort
