## Append samples you want in your CSV to this file as resources ##
resources:
- monitor_v1_centreonservice.yaml
- monitor_v1_centreonservicegroup.yaml
- monitor_v1_template.yaml
- monitor_v1_platform.yaml
    #+kubebuilder:scaffold:manifestskustomizesamples
