apiVersion: monitor.k8s.webcenter.fr/v1alpha1
kind: Platform
metadata:
  name: platform-sample
spec:
  name: centreon
  isDefault: false
  type: centreon
  entreonSettings:
    url: "http://localhost/api"
    selfSignedCertificat: true
    secret: centreon
    endpoint:
      discoverEndpoint: false
