{{- if .Values.createClusterScopedResources -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "monitoring-operator.fullname" . }}
  labels:
    {{- include "monitoring-operator.labels" . | nindent 4 }}
rules:
{{ template "monitoring-operator.rbacRules" $ | toYaml | indent 2 }}
{{- end -}}