{{- if .Values.managedNamespaces -}}
{{- range .Values.managedNamespaces }}
{{- $namespace := . }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespace }}
  labels:
    {{- include "monitoring-operator.labels" $ | nindent 4 }}
    eck.k8s.elastic.co/tenant: {{ $namespace }}
{{- end -}}
{{- end -}}