{{- $operatorNSIsManaged := has .Release.Namespace .Values.managedNamespaces -}}
{{- $fullName := include "monitoring-operator.fullname" . -}}
{{- $svcAccount := include "monitoring-operator.serviceAccountName" . }}

{{- if not .Values.createClusterScopedResources }}
{{- range .Values.managedNamespaces }}
{{- $namespace := . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ $fullName }}"
  namespace: {{ $namespace }}
  labels:
    {{- include "monitoring-operator.labels" $ | nindent 4 }}
rules:
{{ template "monitoring-operator.rbacRules" $ | toYaml | indent 2 }}
{{- end -}} {{- /* end of range over managed namespaces */}}

{{- /* If createClusterScopedResources is false and operator namespace is not in the managed namespaces list, create additional role binding */}}
{{- if not $operatorNSIsManaged }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $fullName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "monitoring-operator.labels" $ | nindent 4 }}
rules:
{{ template "monitoring-operator.rbacRules" $ | toYaml | indent 2 }}
{{- end }} {{- /* end of operator role if operator namespace is not managed */}}
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ $fullName }}-leader-election-role"
  namespace: {{ $.Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch