{{- $operatorNSIsManaged := has .Release.Namespace .Values.managedNamespaces -}}
{{- $fullName := include "monitoring-operator.fullname" . -}}
{{- $svcAccount := include "monitoring-operator.serviceAccountName" . }}

{{- if not .Values.createClusterScopedResources }}
{{- range .Values.managedNamespaces }}
{{- $namespace := . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ $fullName }}"
  namespace: {{ $namespace }}
  labels:
    {{- include "monitoring-operator.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ $fullName }}"
subjects:
- kind: ServiceAccount
  name: {{ $svcAccount }}
  namespace: {{ $.Release.Namespace }}
{{- end }} {{- /* end of range over managed namespaces */}}
{{- /* If createClusterScopedResources is false and operator namespace is not in the managed namespaces list, create additional role binding */}}
{{- if not $operatorNSIsManaged }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ $fullName }}"
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "monitoring-operator.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ $fullName }}"
subjects:
- kind: ServiceAccount
  name: {{ $svcAccount }}
  namespace: {{ $.Release.Namespace }}
{{- end }} {{- /* end of operator role binding if operator namespace is not managed */}}
{{- else }} {{- /* we can create cluster-scoped resources so just create a cluster role binding */}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding 
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "monitoring-operator.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $fullName }}
subjects:
- kind: ServiceAccount
  name: {{ $svcAccount }}
  namespace: {{ $.Release.Namespace }}
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ $fullName }}-leader-election-rolebinding"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ $fullName }}-leader-election-role"
subjects:
- kind: ServiceAccount
  name: {{ include "monitoring-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}