{{- if .Values.monitoring.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitoring-operator.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring-operator.labels" . | nindent 4 }}
type: Opaque
data:
  MONITORING_USERNAME: {{ .Values.monitoring.username | b64enc }}
  MONITORING_PASSWORD: {{ .Values.monitoring.password | b64enc }}
{{- end -}}