# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/monitor.k8s.webcenter.fr_centreonservices.yaml
- bases/monitor.k8s.webcenter.fr_platforms.yaml
- bases/monitor.k8s.webcenter.fr_templates.yaml
- bases/monitor.k8s.webcenter.fr_centreonservicegroups.yaml
#+kubebuilder:scaffold:crdkustomizeresource

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
