name: 'build'

on:
  push:
    branches:
      - main
      - v1alpha1
    tags:
      - '*'
  pull_request:
      branches:
        - main
        - v1alpha1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16' # The Go version to download (if necessary) and use.
    - name: Setup operator-sdk
      uses: jpkrohling/setup-operator-sdk@v1.1.0
      with:
        operator-sdk-version: v1.15.0
    - name: Run build
      run: make build
    - name: Run unit tests
      run: make test
    - uses: codecov/codecov-action@v2
      with:
        files: cover.out
        flags: unittests
        fail_ci_if_error: true
    
  
  acctest-k8s:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - name: Setup operator-sdk
      uses: jpkrohling/setup-operator-sdk@v1.1.0
      with:
        operator-sdk-version: v1.15.0
    - name: Setup Minikube
      uses: manusa/actions-setup-minikube@v2.4.2
      with:
        minikube version: 'v1.23.2'
        kubernetes version: 'v1.21.5'
        driver: docker
        start args: --addons ingress
    - name: Setup Centreon
      run: |
        #!/bin/bash
        set -e
        docker run --name centreon -d --privileged -t -p 80:80 disaster/centreon:21.10-configured
        until $(curl --output /dev/null --silent --head --fail http://localhost/centreon/index.php); do sleep 5; done
    - name: Run acceptance tests
      run: |
        #!/bin/bash
        set -e
        minikube status
        make install
        make run &
        sleep 60
        make test-acc
  
  acctest-openshift:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - name: Setup operator-sdk
      uses: jpkrohling/setup-operator-sdk@v1.1.0
      with:
        operator-sdk-version: v1.15.0
    - name: Setup Microshift
      uses: container-tools/microshift-action@v0.2.1
      with:
        version: '4.8.0'
    - name: Setup Centreon
      run: |
        #!/bin/bash
        set -e
        sudo ufw disable
        docker run --name centreon -d --privileged -t -p 80:80 disaster/centreon:21.10-configured
        until $(curl --output /dev/null --silent --head --fail http://localhost/centreon/index.php); do sleep 5; done
    - name: Run acceptance tests
      run: |
        #!/bin/bash
        set -e
        minikube status
        make install
        make run &
        sleep 60
        make test-acc

  helm-chart-monitoring-operator-crds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Update crds
        run: |
          set -e
          make manifests
          make kustomize
          bin/kustomize build config/crd > deploy/helm/monitoring-operator-crds/templates/all-crds.yaml
      - name: Lint chart
        run: |
          cd deploy/helm/monitoring-operator-crds
          helm lint
      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
      - name: Install chart
        run: |
          cd deploy/helm/monitoring-operator-crds
          helm install monitoring-operatorcrds . -n monitoring-operator --create-namespace --wait
      - name: Publish monitoring-operator-crds helm chart
        uses: goodsmileduck/helm-push-action@v3.3.1
        env:
          SOURCE_DIR: 'deploy/helm'
          CHART_FOLDER: 'monitoring-operator-crds'
          FORCE: 'True'
          CHARTMUSEUM_URL: 'https://charts.webcenter.fr'
          CHARTMUSEUM_USER: '${{ secrets.CHARTMUSEUM_USER }}'
          CHARTMUSEUM_PASSWORD: ${{ secrets.CHARTMUSEUM_PASSWORD }}

  release:
    needs: [acctest-openshift, acctest-k8s]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  release_docker_image:
    needs: [acctest-openshift, acctest-k8s]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses:  docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            webcenter/monitoring-operator
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha
      - uses: little-core-labs/get-git-tag@v3.0.1
        id: tagName
      - name: Commit hash
        id: git
        run: |
          echo ::set-output name=commit_hash::${GITHUB_SHA::8}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: "version=${{ steps.tagName.outputs.tag }},commit=${{ steps.git.outputs.commit_hash }}"

  helm-chart-monitoring-operator:
    needs: [release_docker_image, helm-chart-monitoring-operator-crds]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Lint chart
        run: |
          cd deploy/helm/monitoring-operator
          helm lint
      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
      - name: Install chart
        run: |
          cd deploy/helm/monitoring-operator
          helm dep update
          helm install monitoring-operator . -n monitoring-operator --create-namespace --wait --set monitoring.url=http://localhost/centreon/api/index.php --set monitoring.secret.create=true --set monitoring.username=admin --set monitoring.password=admin
      - uses: little-core-labs/get-git-tag@v3.0.1
        id: tagName
      - uses: mingjun97/file-regex-replace@v1
        with:
          regex: 'version:.*'
          replacement: 'version: "${{ steps.tagName.outputs.tag }}"'
          include: 'Chart\.yaml'
          exclude: 'charts\/.*'
          flags: ''
          path: 'deploy/helm/monitoring-operator'
      - uses: mingjun97/file-regex-replace@v1
        with:
          regex: 'appVersion:.*'
          replacement: 'appVersion: "${{ steps.tagName.outputs.tag }}"'
          include: 'Chart\.yaml'
          exclude: 'charts\/.*'
          flags: ''
          path: 'deploy/helm/monitoring-operator'
      - name: Publish monitoring-operator helm chart
        uses: goodsmileduck/helm-push-action@v3.3.1
        env:
          SOURCE_DIR: 'deploy/helm'
          CHART_FOLDER: 'monitoring-operator'
          FORCE: 'True'
          CHARTMUSEUM_URL: 'https://charts.webcenter.fr'
          CHARTMUSEUM_USER: '${{ secrets.CHARTMUSEUM_USER }}'
          CHARTMUSEUM_PASSWORD: ${{ secrets.CHARTMUSEUM_PASSWORD }}
      